import { auth, api } from '@appdeploy/client';
type Profile={name:string;home:string;work:string;accent:string;photo?:string;saved:unknown[]};type User={userId:string;name?:string;email?:string};type Bridge={profile:()=>Profile;switchProfile:(id:string,p:Profile)=>void;restoreGuest:()=>void;refresh:()=>void;notify:(s:string)=>void;page:()=>string};declare global{interface Window{ollinBeta?:Bridge;}}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));let user:User|null=null,ready=false,busy=false,dirty=false,message='',revision=0;const app=()=>window.ollinBeta!;const safeProfile=(p:Profile):Profile=>({name:p.name||'',home:p.home||'',work:p.work||'',accent:p.accent||'cdmx',saved:Array.isArray(p.saved)?p.saved:[]});
function notify(text:string){message=text;app().notify(text);paint();}
function paint(){const root=document.getElementById('account-root');if(!root)return;if(!ready){root.innerHTML='<span class="beta-eyebrow">TU CUENTA</span><h2>Preparando acceso seguro…</h2>';return;}const disabled=busy?'disabled':'';root.innerHTML=user?`<span class='beta-eyebrow'>CUENTA CONECTADA</span><h2>Tu OLLIN, contigo.</h2><p class='account-id'>${esc(user.email||user.name||'Sesión iniciada')}</p><p>Guarda tu nombre, Casa, Trabajo y favoritos en tu cuenta. La foto y el GPS no se suben.</p><div class='account-actions'><button data-account='save' class='primary' ${disabled}>Guardar en mi cuenta</button><button data-account='load' ${disabled}>Recuperar de mi cuenta</button><button data-account='out' ${disabled}>Cerrar sesión</button><button data-account='delete' class='delete-account' ${disabled}>Eliminar mis datos de OLLIN</button></div><small>${dirty?'Tienes cambios locales sin sincronizar.':'Los datos se sincronizan solo cuando tú lo solicitas.'}</small>`:`<span class='beta-eyebrow'>TU CUENTA</span><h2>Una cuenta. Tu camino.</h2><p>Crea tu cuenta o inicia sesión con los proveedores disponibles en la ventana segura. Puedes seguir explorando como invitado.</p><button data-account='in' class='primary wide' ${disabled}>Crear cuenta o iniciar sesión</button><small>Acceso gestionado por AppDeploy. No guardamos contraseñas en OLLIN. Tu perfil de invitado no se sube automáticamente.</small>`;if(message){const p=document.createElement('p');p.className='account-message';p.setAttribute('role','status');p.textContent=message;root.append(p);}}
async function fetchProfile(){const result=await api.get('/api/me');return result.data.profile as Profile|null;}
async function enter(){const {user:signed}=await auth.signIn();user=signed;ready=true;revision++;app().switchProfile(user!.userId,{name:(signed.name||'').slice(0,40),home:'',work:'',accent:'cdmx',saved:[]});const p=await fetchProfile();if(p)app().switchProfile(user!.userId,safeProfile(p));dirty=false;notify(p?'Sesión iniciada. Recuperamos el perfil guardado en tu cuenta.':'Sesión iniciada. Personaliza tu perfil y toca Guardar en mi cuenta.');}
async function save(){if(!user)return;const p=safeProfile(app().profile());if(!p.name.trim())return notify('Escribe tu nombre y pulsa Guardar perfil antes de sincronizar.');const version=revision;await api.put('/api/me',p);dirty=revision!==version;notify(dirty?'Perfil guardado. Hay cambios posteriores que aún no se han sincronizado.':'Perfil guardado en tu cuenta. Puedes recuperarlo en otro dispositivo.');}
async function load(){if(!user)return;if(dirty&&!confirm('¿Reemplazar los cambios locales con el perfil guardado en tu cuenta?'))return;const version=revision,p=await fetchProfile();if(revision!==version)return notify('El perfil cambió mientras se descargaba. No reemplazamos tus cambios.');if(!p)return notify('Todavía no has guardado un perfil en esta cuenta.');const photo=app().profile().photo;app().switchProfile(user.userId,{...safeProfile(p),photo});dirty=false;notify('Perfil recuperado desde tu cuenta.');}
async function leave(){if(dirty&&!confirm('Hay cambios sin sincronizar. ¿Cerrar sesión y descartarlos?'))return;await auth.signOut();user=null;dirty=false;revision++;app().restoreGuest();notify('Sesión cerrada. Volviste a tu perfil de invitado.');}
async function erase(){if(!user||!confirm('¿Eliminar permanentemente el perfil y los favoritos guardados en tu cuenta de OLLIN? Tu cuenta de Google, Apple, X o AppDeploy no se elimina.'))return;await api.delete('/api/me');await auth.signOut();user=null;dirty=false;revision++;app().restoreGuest();notify('Datos de OLLIN eliminados del servidor. Sesión cerrada.');}
async function initialize(){if(!window.ollinBeta){document.addEventListener('DOMContentLoaded',initialize,{once:true});return;}try{user=await auth.getUser();if(user){app().switchProfile(user.userId,{name:(user.name||'').slice(0,40),home:'',work:'',accent:'cdmx',saved:[]});const p=await fetchProfile();if(p)app().switchProfile(user.userId,safeProfile(p));}}catch{message='No se pudo recuperar la cuenta. Puedes explorar y volver a intentarlo desde Perfil.';}finally{ready=true;paint();}}
window.addEventListener('ollin:render',paint);window.addEventListener('ollin:profile-edited',()=>{revision++;if(user){dirty=true;paint();}});document.addEventListener('click',e=>{const b=(e.target as Element).closest<HTMLButtonElement>('[data-account]');if(!b||busy)return;const action=b.dataset.account;busy=true;message='';paint();const run=action==='in'?enter:action==='save'?save:action==='load'?load:action==='out'?leave:erase;run().catch((error:unknown)=>{const err=error as {code?:string;message?:string;response?:{status?:number}};notify(err.code==='popup_closed'?'Cancelaste el acceso; puedes continuar como invitado.':err.code==='popup_blocked'?'Permite la ventana emergente para crear tu cuenta.':err.response?.status===429?'Límite del servicio alcanzado. No se guardaron cambios. Inténtalo más tarde.':'No se completó la operación de cuenta. Revisa la conexión y vuelve a intentarlo.');}).finally(()=>{busy=false;paint();});});initialize();
